### ISSUE TITLE
Allow the treasury to vote with NEO

### ISSUE THREAD

**Issue by csmuller** [AxLabs/grantshares-contracts#14]
The NEO held in the treasury could be used for voting and, thus, for higher GAS rewards than just from holding it. Implement functionality that handles NEO specifically. Maybe like this:
- NEO is sent to the treasury
- Immediately send the NEO to NeoBurger in the `onNep17Payment` method.
- When NEO funds are released for a proposal, send the necessary amount of 0.001 GAS-multiples to NeoBurger to redeem the NEO and then transfer them to the receiver.
- Have a separate method that allows claiming GAS from NeoBurger

**Comment by gsmachado** [comment]
That's a cool idea. 👍 🥇

**Comment by gsmachado** [comment]
Isn't this implemented?

**Comment by csmuller** [comment]
Yes, you're right. We added a method - which anyone can call - that votes on the committee member with the least votes. Downside is, that method has O(n^2) and will be expensive if we have many more candidates in the future.
