### ISSUE TITLE
Endorse proposal with AxLabs

### ISSUE THREAD

**Issue by csmuller** [AxLabs/grantshares-contracts#25]

**Comment by gsmachado** [comment]
Proposal expired. My last 3-4 days were chaotic. I have to re-create the proposal.

**Comment by csmuller** [comment]
New proposals created. Ready for endorsement.

**Comment by gsmachado** [comment]
Endorsed and voted:

Proposal 4:
endorseProposal: `0xef39d14af2bf57bfb89bbc00b6f6f1dc0fa24603335a22ab06aaa773716c4f91`
vote: `0x100726d39e0e208678650c323d28169f7e5fb9e455684b1c3871d5a4f3505ebb`

Proposal 5:
endorseProposal: `0xb1a7ba1d0421f394efdf9c1427d09fcae08a88cd78016e37d4fe5c2df9e9da92`
vote: `0xc277de7ee48114b0bd00b0963b2a29beeebdbf9b8891dd4895a1253de57a669c`
