### ISSUE TITLE
Tests randomly fail locally and in GitHub actions

### ISSUE THREAD

**Issue by mialbu** [AxLabs/grantshares-contracts#31]
**Observation:**
When executing tests locally and on GitHub actions, tests sometimes fail randomly (different tests fail on different runs).

![image](https://user-images.githubusercontent.com/53603111/169535518-14aecd60-1e92-4765-8cc6-2ec99763c18d.png)

Further, due to ordered tests, tests that depend on a previous test will also fail.

**Comment by csmuller** [comment]
This sometimes happens when generating blocks with neo-express. Nothing we can do about it in this project. Either the test framework of neow3j switches out its underlying blockchain implementation (i.e, neo-express with something else) or this issue is resolved in neo-express itself.
