### ISSUE TITLE
Write test for addFunder method in treasury contract

### ISSUE THREAD

**Issue by csmuller** [AxLabs/grantshares-contracts#7]
The treasury's `addFunder` method can be invoked by a proposal of the governance contract. It needs to be covered by tests that test the following:
- [x] Successfully adding a funder via a governance proposal (is event fired? is new funder in list when calling `getFunders`?)
- [x] Failing to call the `addFunder` method directly (not through the governance contract)

**Comment by bettybao1209** [comment]
close in https://github.com/AxLabs/grantshares-contracts/commit/5bac2015f8c66d5f88e248cfca74415eff329002
